config/routes.rb
Diag::Application.routes.draw do

   root 'welcome#index'

  resources :diagnostiqueurs do
    resources :missions
  end

  resources :diagnostic_amiantes do
    resources :amiantes
  end

  resources :batiments do
    resources :pieces
  end
  
  resources :pieces, shallow: true do
      resources :elements
  end

  

end

app/models/amiante.rb
class Amiante < ActiveRecord::Base
	belongs_to :diagnostic_amiante, :element
end

app/controllers/amiantes_controller.rb
class AmiantesController < ApplicationController
  before_action :set_amiante, only: [:show, :edit, :update, :destroy]

  # GET /amiantes
  # GET /amiantes.json
  def index
    @amiantes = Amiante.all
  end

  # GET /amiantes/1
  # GET /amiantes/1.json
  def show
  end

  # GET /amiantes/new
  def new
    @amiante = Amiante.new
  end

  # GET /amiantes/1/edit
  def edit
  end

  # POST /amiantes
  # POST /amiantes.json
  def create
    @amiante = Amiante.new(amiante_params)

    respond_to do |format|
      if @amiante.save
        format.html { redirect_to @amiante, notice: 'Amiante was successfully created.' }
        format.json { render action: 'show', status: :created, location: @amiante }
      else
        format.html { render action: 'new' }
        format.json { render json: @amiante.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /amiantes/1
  # PATCH/PUT /amiantes/1.json
  def update
    respond_to do |format|
      if @amiante.update(amiante_params)
        format.html { redirect_to @amiante, notice: 'Amiante was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @amiante.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /amiantes/1
  # DELETE /amiantes/1.json
  def destroy
    @amiante.destroy
    respond_to do |format|
      format.html { redirect_to amiantes_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_amiante
      @amiante = Amiante.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def amiante_params
      params.require(:amiante).permit(:identifiant, :composant, :partie_a_sonder, :description, :conclusion, :commentaires)
    end
end

app/helpers/amiantes_helper.rb
module AmiantesHelper
end

app/views/amiantes/_form.html.erb
<%= simple_form_for(@amiante) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :identifiant %>
    <%= f.input :composant %>
    <%= f.input :partie_a_sonder %>
    <%= f.input :description %>
    <%= f.input :conclusion %>
    <%= f.input :commentaires %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/amiantes/edit.html.erb
<h1>Editing amiante</h1>

<%= render 'form' %>

<%= link_to 'Show', @amiante %> |
<%= link_to 'Back', amiantes_path %>

app/views/amiantes/index.html.erb
<h1>Listing amiantes</h1>

<table>
  <thead>
    <tr>
      <th>Identifiant</th>
      <th>Composant</th>
      <th>Partie a sonder</th>
      <th>Description</th>
      <th>Conclusion</th>
      <th>Commentaires</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @amiantes.each do |amiante| %>
      <tr>
        <td><%= amiante.identifiant %></td>
        <td><%= amiante.composant %></td>
        <td><%= amiante.partie_a_sonder %></td>
        <td><%= amiante.description %></td>
        <td><%= amiante.conclusion %></td>
        <td><%= amiante.commentaires %></td>
        <td><%= link_to 'Show', amiante %></td>
        <td><%= link_to 'Edit', edit_amiante_path(amiante) %></td>
        <td><%= link_to 'Destroy', amiante, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Amiante', new_amiante_path %>

app/views/amiantes/new.html.erb
<h1>New amiante</h1>

<%= render 'form' %>

<%= link_to 'Back', amiantes_path %>

app/views/amiantes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Identifiant:</strong>
  <%= @amiante.identifiant %>
</p>

<p>
  <strong>Composant:</strong>
  <%= @amiante.composant %>
</p>

<p>
  <strong>Partie a sonder:</strong>
  <%= @amiante.partie_a_sonder %>
</p>

<p>
  <strong>Description:</strong>
  <%= @amiante.description %>
</p>

<p>
  <strong>Conclusion:</strong>
  <%= @amiante.conclusion %>
</p>

<p>
  <strong>Commentaires:</strong>
  <%= @amiante.commentaires %>
</p>

<%= link_to 'Edit', edit_amiante_path(@amiante) %> |
<%= link_to 'Back', amiantes_path %>