config/routes.rb
Diag::Application.routes.draw do

   root 'welcome#index'

  resources :diagnostiqueurs do
    resources :missions
  end

  resources :diagnostic_amiantes do
    resources :amiantes
  end

  resources :batiments do
    resources :pieces
  end
  
  resources :pieces, shallow: true do
      resources :elements
  end

  

end

app/models/diagnostiqueur.rb
class Diagnostiqueur < ActiveRecord::Base
	has_many :missions
end

app/controllers/diagnostiqueurs_controller.rb
class DiagnostiqueursController < ApplicationController
  before_action :set_diagnostiqueur, only: [:show, :edit, :update, :destroy]

  # GET /diagnostiqueurs
  # GET /diagnostiqueurs.json
  def index
    @diagnostiqueurs = Diagnostiqueur.all
  end

  # GET /diagnostiqueurs/1
  # GET /diagnostiqueurs/1.json
  def show
  end

  # GET /diagnostiqueurs/new
  def new
    @diagnostiqueur = Diagnostiqueur.new
  end

  # GET /diagnostiqueurs/1/edit
  def edit
  end

  # POST /diagnostiqueurs
  # POST /diagnostiqueurs.json
  def create
    @diagnostiqueur = Diagnostiqueur.new(diagnostiqueur_params)

    respond_to do |format|
      if @diagnostiqueur.save
        format.html { redirect_to @diagnostiqueur, notice: 'Diagnostiqueur was successfully created.' }
        format.json { render action: 'show', status: :created, location: @diagnostiqueur }
      else
        format.html { render action: 'new' }
        format.json { render json: @diagnostiqueur.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /diagnostiqueurs/1
  # PATCH/PUT /diagnostiqueurs/1.json
  def update
    respond_to do |format|
      if @diagnostiqueur.update(diagnostiqueur_params)
        format.html { redirect_to @diagnostiqueur, notice: 'Diagnostiqueur was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @diagnostiqueur.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /diagnostiqueurs/1
  # DELETE /diagnostiqueurs/1.json
  def destroy
    @diagnostiqueur.destroy
    respond_to do |format|
      format.html { redirect_to diagnostiqueurs_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_diagnostiqueur
      @diagnostiqueur = Diagnostiqueur.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def diagnostiqueur_params
      params.require(:diagnostiqueur).permit(:nom, :prenom, :raison_sociale, :num_certif, :validite_certif, :obtention_certif, :adresse, :code_postal, :commune, :tel, :email, :num_tva, :siret, :nom_assureur, :coordonnees_assureur, :num_assurance, :validite_assurance)
    end
end

app/helpers/diagnostiqueurs_helper.rb
module DiagnostiqueursHelper
end

app/views/diagnostiqueurs/_form.html.erb
<%= simple_form_for(@diagnostiqueur) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :nom %>
    <%= f.input :prenom %>
    <%= f.input :raison_sociale %>
    <%= f.input :num_certif %>
    <%= f.input :validite_certif %>
    <%= f.input :obtention_certif %>
    <%= f.input :adresse %>
    <%= f.input :code_postal %>
    <%= f.input :commune %>
    <%= f.input :tel %>
    <%= f.input :email %>
    <%= f.input :num_tva %>
    <%= f.input :siret %>
    <%= f.input :nom_assureur %>
    <%= f.input :coordonnees_assureur %>
    <%= f.input :num_assurance %>
    <%= f.input :validite_assurance %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/diagnostiqueurs/edit.html.erb
<h1>Editing diagnostiqueur</h1>

<%= render 'form' %>

<%= link_to 'Show', @diagnostiqueur %> |
<%= link_to 'Back', diagnostiqueurs_path %>

app/views/diagnostiqueurs/index.html.erb
<h1>Listing diagnostiqueurs</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Nom</th>
      <th>Prenom</th>
      <th>Raison sociale</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @diagnostiqueurs.each do |diagnostiqueur| %>
      <tr>
        <td><%= diagnostiqueur.nom %></td>
        <td><%= diagnostiqueur.prenom %></td>
        <td><%= diagnostiqueur.raison_sociale %></td>
        
        <td><%= link_to 'Show', diagnostiqueur %></td>
        <td><%= link_to 'Edit', edit_diagnostiqueur_path(diagnostiqueur) %></td>
        <td><%= link_to 'Destroy', diagnostiqueur, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Diagnostiqueur', new_diagnostiqueur_path %>

app/views/diagnostiqueurs/new.html.erb
<h1>New diagnostiqueur</h1>

<%= render 'form' %>

<%= link_to 'Back', diagnostiqueurs_path %>

app/views/diagnostiqueurs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nom:</strong>
  <%= @diagnostiqueur.nom %>
</p>

<p>
  <strong>Prenom:</strong>
  <%= @diagnostiqueur.prenom %>
</p>

<p>
  <strong>Raison sociale:</strong>
  <%= @diagnostiqueur.raison_sociale %>
</p>

<p>
  <strong>Num certif:</strong>
  <%= @diagnostiqueur.num_certif %>
</p>

<p>
  <strong>Validite certif:</strong>
  <%= @diagnostiqueur.validite_certif %>
</p>

<p>
  <strong>Obtention certif:</strong>
  <%= @diagnostiqueur.obtention_certif %>
</p>

<p>
  <strong>Adresse:</strong>
  <%= @diagnostiqueur.adresse %>
</p>

<p>
  <strong>Code postal:</strong>
  <%= @diagnostiqueur.code_postal %>
</p>

<p>
  <strong>Commune:</strong>
  <%= @diagnostiqueur.commune %>
</p>

<p>
  <strong>Tel:</strong>
  <%= @diagnostiqueur.tel %>
</p>

<p>
  <strong>Email:</strong>
  <%= @diagnostiqueur.email %>
</p>

<p>
  <strong>Num tva:</strong>
  <%= @diagnostiqueur.num_tva %>
</p>

<p>
  <strong>Siret:</strong>
  <%= @diagnostiqueur.siret %>
</p>

<p>
  <strong>Nom assureur:</strong>
  <%= @diagnostiqueur.nom_assureur %>
</p>

<p>
  <strong>Coordonnees assureur:</strong>
  <%= @diagnostiqueur.coordonnees_assureur %>
</p>

<p>
  <strong>Num assurance:</strong>
  <%= @diagnostiqueur.num_assurance %>
</p>

<p>
  <strong>Validite assurance:</strong>
  <%= @diagnostiqueur.validite_assurance %>
</p>

<%= link_to 'Edit', edit_diagnostiqueur_path(@diagnostiqueur) %> |
<%= link_to 'Back', diagnostiqueurs_path %>
<p> <%= link_to 'Add Mission', new_diagnostiqueur_mission_path(@diagnostiqueur) %> </p>