config/routes.rb
Diag::Application.routes.draw do

   root 'welcome#index'

  resources :diagnostiqueurs do
    resources :missions
  end

  resources :diagnostic_amiantes do
    resources :amiantes
  end

  resources :batiments do
    resources :pieces
  end
  
  resources :pieces, shallow: true do
      resources :elements
  end

  

end

app/models/batiment.rb
class Batiment < ActiveRecord::Base
	has_many :pieces, dependent: :destroy
	belongs_to :mission
	validates :adresse, presence: true, length: {minimum: 5}
	validates :designation, presence: true, length: {minimum: 5}
	validates :code_postal, presence: true, length: {is: 5}
	validates :commune, presence: true, length: {minimum: 5}
end

app/controllers/batiments_controller.rb
class BatimentsController < ApplicationController
	
	def index
		@batiments = Batiment.all
	end
	def new
		@batiment = Batiment.new
	end

	def create
		@batiment = Batiment.new(batiment_params)
		
		if @batiment.save
			flash[:notice] = "Bâtiment créé!"
			redirect_to new_batiment_piece_path(@batiment)
		else
			render('new')
		end
	end

	def show
		@batiment = Batiment.find(params[:id])
		@piece = @batiment.pieces.build
	end

	def edit
		@batiment = Batiment.find(params[:id])
	end

	def update
		@batiment = Batiment.find(params[:id])
		if @batiment.update_attributes(batiment_params)
			flash[:notice] = "Bâtiment modifié!"
			redirect_to @batiment
		else
			render 'edit'
		end	
	end

	def delete
		@batiment = Batiment.find(params[:id])
	end

	def destroy
		batiment = Batiment.find(params[:id]).destroy
		flash[:notice] = "Bâtiment supprimé!"
		redirect_to batiments_path
	end

	private
	#pour create - sécurité
	def batiment_params
    params.require(:batiment).permit(:adresse, :designation, :code_postal, :commune)
  end

end

app/helpers/batiments_helper.rb
module BatimentsHelper
end

app/views/batiments/_form.html.erb
<%= simple_form_for :batiment, url: batiments_path, html: { class: 'form-horizontal' } do |f|  %>
	 <% if @batiment.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@batiment.errors.count, "erreur") %> empêchent
      ce batiment d'être enregistré:</h2>
    <ul>
    <% @batiment.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>

  <%= f.input :adresse %>
  <%= f.input :designation %>
  <%= f.input :code_postal %>
  <%= f.input :commune %>
  <%= f.button :submit, :class => 'btn btn-large btn-primary' %>
<% end %>

app/views/batiments/edit.html.erb
<h1>Modifier Bâtiment</h1>

<%= render 'form' %>

<%= link_to "Retour",batiments_path %>

app/views/batiments/index.html.erb
<% if !flash[:notice].blank? %>
  <div class="bg-success">
    <%= flash[:notice] %>
  </div>
<% end %>

<%= link_to "Nouveau bâtiment",new_batiment_path %>

<h1>Liste des batiments</h1>
 
<table class="table table-striped">
  <tr>
    <th>Adresse</th>
    <th>Désignation</th>
    <th>CP</th>
    <th>Commune</th>
  </tr>
 
  <% @batiments.each do |batiment| %>
    <tr>
      <td><%= batiment.adresse %></td>
      <td><%= batiment.designation %></td>
      <td><%= batiment.code_postal %></td>
      <td><%= batiment.commune %></td>
      <td><%= link_to "Voir", batiment %> </td>
      <td><%= link_to "Modifier", edit_batiment_path(batiment) %> </td>
      <td><%= link_to "Supprimer", batiment_path(batiment), method: :delete, data: { confirm: "Êtes-vous sûr?"} %></td>
    </tr>
  <% end %>
</table>

app/views/batiments/new.html.erb
<h1>Nouveau Bâtiment</h1>

<%= render 'form' %>

<%= link_to "Retour",batiments_path %>

app/views/batiments/show.html.erb
<h1>Batiment</h1>
<p>
  <strong>Adresse:</strong>
  <%= @batiment.adresse %>
</p>
<p>
  <strong>Désignation et situation du ou des lots de copropriété:</strong>
  <%= @batiment.designation %>
</p>
<p>
  <strong>Code postal:</strong>
  <%= @batiment.code_postal %>
</p>
<p>
  <strong>Commune:</strong>
  <%= @batiment.commune %>
</p>
<h2>Pièces</h2>

<table class="table table-striped">
 	<tr>
   	<th>Pièce</th>
  </tr>

  <% @batiment.pieces.each do |piece| %>
		<tr>
		  <td> <%= piece.nom %> <%= piece.numero %> </td>
		  <td><%= link_to 'Voir', piece %> </td>      
    </tr>
  <% end %>
</table>	



<h2>Ajouter une Pièce</h2>
<%= render 'pieces/form' %>

<%= link_to "Retour",batiments_path %>
<%= link_to "Modifier", edit_batiment_path(@batiment) %>