config/routes.rb
Diag::Application.routes.draw do

   root 'welcome#index'

  resources :diagnostiqueurs do
    resources :missions
  end

  resources :diagnostic_amiantes do
    resources :amiantes
  end

  resources :batiments do
    resources :pieces
  end
  
  resources :pieces, shallow: true do
      resources :elements
  end

  

end

app/models/mission.rb
class Mission < ActiveRecord::Base
	belongs_to :diagnostiqueur
	has_one :batiment
	has_one :diagnostic_amiante
end

app/controllers/missions_controller.rb
class MissionsController < ApplicationController
  before_action :set_mission, only: [:show, :edit, :update, :destroy]
  before_action :set_diagnostiqueur, only: [:new, :create,:show]

  # GET /missions
  # GET /missions.json
  def index
    @missions = Mission.all
  end

  # GET /missions/1
  # GET /missions/1.json
  def show
  end

  # GET /missions/new
  def new
    @mission = @diagnostiqueur.missions.new
  end

  # GET /missions/1/edit
  def edit
  end

  # POST /missions
  # POST /missions.json
  def create
    @mission = @diagnostiqueur.missions.new(mission_params)

    respond_to do |format|
      if @mission.save
        format.html { redirect_to new_batiment_path, notice: 'Mission was successfully created.' }
        format.json { render action: 'show', status: :created, location: @mission }
      else
        format.html { render action: 'new' }
        format.json { render json: @mission.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /missions/1
  # PATCH/PUT /missions/1.json
  def update
    respond_to do |format|
      if @mission.update(mission_params)
        format.html { redirect_to @mission, notice: 'Mission was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @mission.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /missions/1
  # DELETE /missions/1.json
  def destroy
    @mission.destroy
    respond_to do |format|
      format.html { redirect_to diagnostiqueur_missions_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_diagnostiqueur
      @diagnostiqueur = Diagnostiqueur.find(params[:diagnostiqueur_id])
    end
    def set_mission
      @mission = Mission.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def mission_params
      params.require(:mission).permit(:num_dossier, :date_reperage, :heure_reperage, :duree_reperage, :top_amiante, :perimetre_reperage, :dateheure_visite, :deadline_rapport, :date_emission_rapport)
    end
end

app/helpers/missions_helper.rb
module MissionsHelper
end

app/views/missions/_form.html.erb
<%= simple_form_for([@mission.diagnostiqueur,@mission]) do |f| %>
  <%= f.error_notification %>

  <div class="form-horizontal">
    <%= f.input :num_dossier %>
    <%= f.input :date_reperage %>
    <%= f.input :heure_reperage %>
    <%= f.input :duree_reperage %>
    <%= f.input :top_amiante %>
    <%= f.input :perimetre_reperage %>
    <%= f.input :dateheure_visite %>
    <%= f.input :deadline_rapport %>
    <%= f.input :date_emission_rapport %>
  </div>

  <div class="form-actions">
    <%= f.button :submit , :class => 'btn btn-large btn-primary'%>
  </div>
<% end %>

app/views/missions/edit.html.erb
<h1>Editing mission</h1>

<%= render 'form' %>

<%= link_to 'Show', diagnostiqueur_mission_path(@mission.diagnostiqueur,@mission) %> |
<%= link_to 'Back', diagnostiqueur_missions_path(@mission.diagnostiqueur) %>

app/views/missions/index.html.erb
<h2>Liste des missions réalisées par <%= @missions.first.diagnostiqueur.prenom %> <%= @missions.first.diagnostiqueur.nom %> de <%= @missions.first.diagnostiqueur.raison_sociale %></h2>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Num dossier</th>
      <th>Date reperage</th>
      
      <th>Top amiante</th>
      <th>Adresse</th>
      <th>Perimetre reperage</th>
      <th>Dateheure visite</th>
      <th>Deadline rapport</th>
      <th>Date emission rapport</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @missions.each do |mission| %>
      <tr>
        <td><%= mission.num_dossier %></td>
        <td><%= mission.date_reperage %></td>
        
        <td><%= mission.top_amiante %></td>
        <td><%= mission.batiment.adresse %> <%= mission.batiment.code_postal %> </td>
        <td><%= mission.perimetre_reperage %></td>
        <td><%= mission.dateheure_visite %></td>
        <td><%= mission.deadline_rapport %></td>
        <td><%= mission.date_emission_rapport %></td>
        <td><%= link_to 'Show', diagnostiqueur_mission_path(mission.diagnostiqueur,mission) %></td>
        <td><%= link_to 'Edit', edit_diagnostiqueur_mission_path(mission.diagnostiqueur,mission) %></td>
        <td><%= link_to 'Destroy', diagnostiqueur_mission_path(mission.diagnostiqueur,mission), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Mission', new_diagnostiqueur_mission_path %>

app/views/missions/new.html.erb
<h1>New mission</h1>

<%= render 'form' %>

<p><%= link_to 'Back', diagnostiqueur_missions_path %></p>

app/views/missions/show.html.erb
<p id="notice"><%= notice %></p>

<h2>Bâtiment:</h2>
<p> <% bat = @mission.batiment %>
    <%= bat.adresse %> , <%=bat.code_postal %> <%=bat.commune %></p>
<p>
  <strong>Num dossier:</strong>
  <%= @mission.num_dossier %>
</p>

<p>
  <strong>Date reperage:</strong>
  <%= @mission.date_reperage %>
</p>

<p>
  <strong>Heure reperage:</strong>
  <%= @mission.heure_reperage %>
</p>

<p>
  <strong>Duree reperage:</strong>
  <%= @mission.duree_reperage %>
</p>

<p>
  <strong>Top amiante:</strong>
  <%= @mission.top_amiante %>
</p>

<p>
  <strong>Perimetre reperage:</strong>
  <%= @mission.perimetre_reperage %>
</p>

<p>
  <strong>Dateheure visite:</strong>
  <%= @mission.dateheure_visite %>
</p>

<p>
  <strong>Deadline rapport:</strong>
  <%= @mission.deadline_rapport %>
</p>

<p>
  <strong>Date emission rapport:</strong>
  <%= @mission.date_emission_rapport %>
</p>

<%= link_to 'Edit', edit_diagnostiqueur_mission_path(@diagnostiqueur,@mission) %> |
<%= link_to 'Back', diagnostiqueur_missions_path %>